/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/astryx/y2k/y2kTheme.ts
 * Command: astryx theme build src/themes/astryx/y2k/y2kTheme.ts
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const y2kIconRegistry: IconRegistry;
export declare const y2kTheme: DefinedTheme;
