/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/astryx/stone/stoneTheme.ts
 * Command: astryx theme build src/themes/astryx/stone/stoneTheme.ts
 * CLI: @astryxdesign/cli@0.6.5
 * Core: @astryxdesign/core@0.6.5
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const stoneIconRegistry: IconRegistry;
export declare const stoneTheme: DefinedTheme;
