/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/neutral/neutralTheme.ts, src/themes/neutral/variants/amber.ts, src/themes/neutral/variants/amber-hc.ts, src/themes/neutral/variants/claude.ts, src/themes/neutral/variants/claude-hc.ts, src/themes/neutral/variants/lavender.ts, src/themes/neutral/variants/lavender-hc.ts, src/themes/neutral/variants/lime.ts, src/themes/neutral/variants/lime-hc.ts, src/themes/neutral/variants/neon.ts, src/themes/neutral/variants/neon-hc.ts, src/themes/neutral/variants/ocean.ts, src/themes/neutral/variants/ocean-hc.ts, src/themes/neutral/variants/rose.ts, src/themes/neutral/variants/rose-hc.ts, src/themes/neutral/variants/sage.ts, src/themes/neutral/variants/sage-hc.ts, src/themes/neutral/variants/slate.ts, src/themes/neutral/variants/slate-hc.ts
 * Command: bunx astryx theme build --family src/themes/neutral/neutralTheme.ts src/themes/neutral/variants/amber.ts src/themes/neutral/variants/amber-hc.ts src/themes/neutral/variants/claude.ts src/themes/neutral/variants/claude-hc.ts src/themes/neutral/variants/lavender.ts src/themes/neutral/variants/lavender-hc.ts src/themes/neutral/variants/lime.ts src/themes/neutral/variants/lime-hc.ts src/themes/neutral/variants/neon.ts src/themes/neutral/variants/neon-hc.ts src/themes/neutral/variants/ocean.ts src/themes/neutral/variants/ocean-hc.ts src/themes/neutral/variants/rose.ts src/themes/neutral/variants/rose-hc.ts src/themes/neutral/variants/sage.ts src/themes/neutral/variants/sage-hc.ts src/themes/neutral/variants/slate.ts src/themes/neutral/variants/slate-hc.ts --family-key neutral-family
 * CLI: @astryxdesign/cli@0.6.5
 * Core: @astryxdesign/core@0.6.5
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const neutralTheme: DefinedTheme;
export declare const neutralAmberTheme: DefinedTheme;
export declare const neutralAmberHcTheme: DefinedTheme;
export declare const neutralClaudeTheme: DefinedTheme;
export declare const neutralClaudeHcTheme: DefinedTheme;
export declare const neutralLavenderTheme: DefinedTheme;
export declare const neutralLavenderHcTheme: DefinedTheme;
export declare const neutralLimeTheme: DefinedTheme;
export declare const neutralLimeHcTheme: DefinedTheme;
export declare const neutralNeonTheme: DefinedTheme;
export declare const neutralNeonHcTheme: DefinedTheme;
export declare const neutralOceanTheme: DefinedTheme;
export declare const neutralOceanHcTheme: DefinedTheme;
export declare const neutralRoseTheme: DefinedTheme;
export declare const neutralRoseHcTheme: DefinedTheme;
export declare const neutralSageTheme: DefinedTheme;
export declare const neutralSageHcTheme: DefinedTheme;
export declare const neutralSlateTheme: DefinedTheme;
export declare const neutralSlateHcTheme: DefinedTheme;

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
