/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/astryx/butter/butterTheme.ts
 * Command: astryx theme build src/themes/astryx/butter/butterTheme.ts
 * CLI: @astryxdesign/cli@0.6.5
 * Core: @astryxdesign/core@0.6.5
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Card' {
  interface CardVariantMap {
    'info': true;
    'success': true;
    'warning': true;
    'error': true;
  }
}
