/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/astryx/butter/butterTheme.ts
 * Command: astryx theme build src/themes/astryx/butter/butterTheme.ts
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

/// <reference path="./butter.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const butterIconRegistry: IconRegistry;
export declare const butterTheme: DefinedTheme;
