/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/astryx/chocolate/chocolateTheme.ts
 * Command: astryx theme build src/themes/astryx/chocolate/chocolateTheme.ts
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const chocolateIconRegistry: IconRegistry;
export declare const chocolateTheme: DefinedTheme;
