// Which rewrite queries use the real backend when BACKEND_URL is set. Any
// missing live implementation must be named and explained: an unlisted mock
// fallback is a parity regression, not a harmless default.
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { liveQueryNames } from '../src/data/api'
import { queryNames } from '../src/data/backend'

export type Exception = {
  status: 'local' | 'mock-only' | 'unused'
  reason: string
}

export const BACKEND_EXCEPTIONS: Record<string, Exception> = {
  getReplay: {
    status: 'local',
    reason:
      'Production replay pages and downloads use getReplayDetail and raw download handlers; this is the no-backend mock fallback.',
  },
  getSessionSummary: {
    status: 'unused',
    reason: 'No rewrite route or component calls this legacy query.',
  },
  resolveIncidents: {
    status: 'local',
    reason:
      'Mock-scenario control; it is not part of the production backend contract.',
  },
  simulateIncident: {
    status: 'local',
    reason:
      'Mock-scenario control; it is not part of the production backend contract.',
  },
}

export function renderBackendCoverage(
  all = queryNames(),
  live = liveQueryNames(),
): string {
  const liveNames = new Set(live)
  const rows = [...all]
    .sort()
    .map((name) => ({
      name,
      ...(liveNames.has(name)
        ? {
            status: 'live' as const,
            reason: 'Implemented by `src/data/api.ts`.',
          }
        : BACKEND_EXCEPTIONS[name]),
    }))
  const count = (status: string) =>
    rows.filter((row) => row.status === status).length
  return [
    '# Backend query coverage',
    '',
    'Every query in the rewrite data facade and what answers it when `BACKEND_URL` is set. Generated by `bun scripts/backend-coverage.ts`; `src/test/backend-coverage.test.ts` fails on an unexplained fallback.',
    '',
    `**${rows.length} queries**: ${count('live')} live, ${count('local')} intentionally local, ${count('unused')} unused, ${count('mock-only')} mock-only.`,
    '',
    '> Cutover gate: every **mock-only** row used by a production route needs a real adapter or an explicitly accepted product deviation. Until then the proof is complete but the traffic switch is **NO-GO**.',
    '',
    '| Query | Production answer | Reason |',
    '|---|---|---|',
    ...rows.map((row) => `| \`${row.name}\` | ${row.status} | ${row.reason} |`),
    '',
  ].join('\n')
}

if (import.meta.main) {
  const path = join(
    import.meta.dirname,
    '..',
    'docs/migration/backend-coverage.md',
  )
  writeFileSync(path, renderBackendCoverage())
  console.log(
    `docs/migration/backend-coverage.md: ${queryNames().length} queries`,
  )
}
