// Writes src/data/queries.ts: one server function per query of the mock
// backend, spelled out because Start's compiler only finds server functions
// declared statically. Pages call the exports with the query's own
// arguments; the handler runs the query on the server, in the page's mock
// scenario.
//
//   bun scripts/gen-queries.ts           write
//   bun scripts/gen-queries.ts --check   fail when the file is stale (tests)
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { queryNames } from '../src/data/backend'
import { isRead } from '../src/data/scenario'

const root = join(import.meta.dirname, '..')
const implSource = readFileSync(join(root, 'src/data/queries.impl.ts'), 'utf8')
const types = [...implSource.matchAll(/^export (?:type|interface) (\w+)/gm)].map((m) => m[1]).sort()

export function renderQueries(): string {
  const names = queryNames().sort()
  const lines = [
    '// Generated by scripts/gen-queries.ts from src/data/queries.impl.ts: do not edit.',
    '//',
    '// The data seam every page imports. Each query is a server function: the',
    '// page calls it with the query\'s own arguments, the handler runs it on the',
    '// server against the mock backend (src/data/backend.ts) in the page\'s mock',
    '// scenario. The mock never reaches the browser. Wiring the real backend',
    '// replaces the backend behind the handlers; these signatures stay.',
    "import { createServerFn } from '@tanstack/react-start'",
    "import type * as impl from './queries.impl'",
    "import { announced, mockScenarioMiddleware } from './serverFn'",
    "import type { Json } from './serverFn'",
    '',
    "export { alertKeyOf, generatePassword, inRange, redact } from './shared'",
    `export type { ${types.join(', ')} } from './queries.impl'`,
    '',
    '/** The server function for one query, called like the query itself. */',
    'type Rpc<TQuery> = TQuery',
    '',
  ]
  for (const name of names) {
    lines.push(
      `const ${name}Fn = createServerFn({ method: '${isRead(name) ? 'GET' : 'POST'}' })`,
      '  .middleware([mockScenarioMiddleware])',
      '  .validator((args: unknown[]) => args)',
      `  .handler(async ({ data, context }) => (await (await import('./backend')).runForRequest('${name}', data, context.mock)) as Json)`,
      `export const ${name} = announced('${name}', ${name}Fn) as Rpc<typeof impl.${name}>`,
      '',
    )
  }
  return lines.join('\n')
}

if (import.meta.main) {
  const path = join(root, 'src/data/queries.ts')
  const next = renderQueries()
  if (process.argv.includes('--check')) {
    if (readFileSync(path, 'utf8') !== next) {
      console.error('src/data/queries.ts is stale: run bun scripts/gen-queries.ts')
      process.exit(1)
    }
  } else {
    writeFileSync(path, next)
    console.log(`src/data/queries.ts: ${queryNames().length} server functions`)
  }
}
