// Field coverage: every field a canonical page reads (docs/migration/
// routes.json) against the mock data the rewrite's pages show. A field is
// covered when the rewrite's data types carry a field of the same name
// (case and separators ignored), mapped when docs/migration/field-map.json
// names the rewrite field that carries it under another name, waived when
// that file says why the page does not need it, and a gap otherwise.
//
//   bun scripts/inventory/field-coverage.ts   writes docs/migration/field-coverage.md
//
// src/test/field-coverage.test.ts fails on a gap or a stale document.
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { RouteInventory } from './routes'

const root = join(import.meta.dirname, '..', '..')
const dir = join(root, 'docs/migration')

/** route → canonical field (as routes.json writes it) → `rewrite field`
 * or `waived: reason`. */
export type FieldMap = Record<string, Record<string, string>>

export type Coverage = {
  route: string
  fields: number
  covered: number
  mapped: Array<{ field: string; to: string }>
  waived: Array<{ field: string; reason: string }>
  gaps: string[]
}

const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '')
/** The part of a field path that names the value: `rows[].src_ip` → src_ip. */
export const leafOf = (field: string) => field.split('.').pop()!.replace(/\[\]$/, '').replace(/^@/, '')

export function coverage(routes: RouteInventory[], map: FieldMap, types: string): Coverage[] {
  const corpus = norm(types)
  return routes.map((r) => {
    const fields = [...new Set(r.reads.flatMap((read) => read.fields))].filter((f) => {
      const leaf = leafOf(f)
      return leaf !== '' && !/^\d+$/.test(leaf)
    })
    const own = map[r.route] ?? {}
    const result: Coverage = { route: r.route, fields: fields.length, covered: 0, mapped: [], waived: [], gaps: [] }
    for (const field of fields) {
      const entry = own[field] as string | undefined
      if (entry?.startsWith('waived: ')) result.waived.push({ field, reason: entry.slice(8) })
      else if (entry) result.mapped.push({ field, to: entry })
      else if (corpus.includes(norm(leafOf(field)))) result.covered += 1
      else result.gaps.push(field)
    }
    return result
  })
}

/** Map entries that name a field the route no longer reads. */
export function staleEntries(routes: RouteInventory[], map: FieldMap): string[] {
  return Object.entries(map).flatMap(([route, fields]) => {
    const r = routes.find((x) => x.route === route)
    const read = new Set(r?.reads.flatMap((x) => x.fields) ?? [])
    return Object.keys(fields).filter((f) => !read.has(f)).map((f) => `${route}: ${f}`)
  })
}

export function renderCoverage(rows: Coverage[]): string {
  const sum = (pick: (c: Coverage) => number) => rows.reduce((n, c) => n + pick(c), 0)
  const cell = (t: string) => t.replace(/\|/g, '\\|')
  const lines = [
    '# Field coverage',
    '',
    'Every field a canonical page reads (`routes.json`) against the mock data the rewrite shows. **Covered**: the rewrite\'s data types carry a field of that name. **Mapped**: carried under another name, per `field-map.json`. **Waived**: not needed, with the reason. **Gap**: still to add to the mock data and the page. Generated by `scripts/inventory/field-coverage.ts`; a name match says the data exists, the page review says it is shown.',
    '',
    `**${sum((c) => c.fields)} fields** on ${rows.length} pages: ${sum((c) => c.covered)} covered, ${sum((c) => c.mapped.length)} mapped, ${sum((c) => c.waived.length)} waived, **${sum((c) => c.gaps.length)} gaps**.`,
    '',
    '| Page | Fields | Covered | Mapped | Waived | Gaps |',
    '|---|---|---|---|---|---|',
    ...rows.map((c) => `| \`${c.route}\` | ${c.fields} | ${c.covered} | ${c.mapped.length} | ${c.waived.length} | ${c.gaps.length || ''} |`),
    '',
  ]
  for (const c of rows.filter((x) => x.gaps.length || x.mapped.length || x.waived.length)) {
    lines.push(`## \`${c.route}\``, '')
    if (c.gaps.length) lines.push(`**Gaps:** ${c.gaps.map((f) => `\`${cell(f)}\``).join(', ')}`, '')
    for (const m of c.mapped) lines.push(`- \`${cell(m.field)}\` → ${cell(m.to)}`)
    for (const w of c.waived) lines.push(`- \`${cell(w.field)}\`: waived, ${cell(w.reason)}`)
    if (c.mapped.length || c.waived.length) lines.push('')
  }
  return lines.join('\n')
}

export function build() {
  const routes = JSON.parse(readFileSync(join(dir, 'routes.json'), 'utf8')) as RouteInventory[]
  const map = JSON.parse(readFileSync(join(dir, 'field-map.json'), 'utf8')) as FieldMap
  const types = readFileSync(join(root, 'src/data/types.ts'), 'utf8')
  const rows = coverage(routes, map, types)
  return { rows, stale: staleEntries(routes, map), markdown: renderCoverage(rows) }
}

if (import.meta.main) {
  const { rows, stale, markdown } = build()
  if (stale.length) {
    console.error('field-map.json names fields the routes do not read:', stale)
    process.exit(1)
  }
  writeFileSync(join(dir, 'field-coverage.md'), markdown)
  console.log(`docs/migration/field-coverage.md: ${rows.reduce((n, c) => n + c.gaps.length, 0)} gaps`)
}
