// Phase 2 slices (#6): the canonical dashboard cut into bounded migration
// issues by operator workflow. Every canonical route module belongs to
// exactly one slice; every server function to the slice of the routes that
// use it (shared ones to the shell slice). The inventory documents link
// each row to its slice's issue.
//
//   bun scripts/inventory/slices.ts            writes docs/migration/slices.md
//   bun scripts/inventory/slices.ts --create   files the slice issues first
//                                              (once; numbers kept in slices.json)
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { ROWS } from '../route-matrix'
import type { RouteInventory } from './routes'
import type { ServerFn } from './server-functions'
import { SLICES, issueNumbers, sliceOfFn } from './slice-map'
import type { Slice } from './slice-map'

const dir = join(import.meta.dirname, '..', '..', 'docs/migration')
const read = <T>(name: string): T => JSON.parse(readFileSync(join(dir, name), 'utf8')) as T

function body(slice: Slice, fns: ServerFn[], routes: RouteInventory[]): string {
  const rows = ROWS.filter((r) => slice.routes.includes(r.source))
  const pages = routes.filter((r) => slice.routes.includes(r.route))
  const own = fns.filter((f) => sliceOfFn(f, routes) === slice.key)
  const states = [...new Set(pages.flatMap((p) => p.states))]
  const fnLine = (f: ServerFn) => `- \`${f.file.replace(/^src\//, '')}#${f.name}\` ${f.method}, ${f.permission}${f.backend.length ? `: ${f.backend.map((b) => `\`${b}\``).join(', ')}` : ''}`
  return [
    `Part of #6 (Phase 2). Workflow: ${slice.workflow}`,
    '',
    'Wire this workflow to the real backend behind the data seam the mock pages already use (`src/data/queries.ts`), keeping the pages as they are. The rows below come from the inventory in `docs/migration/` (`route-matrix.md`, `routes.md`, `server-functions.md`); tick them there as they become real.',
    '',
    '## Routes',
    '',
    ...rows.map((r) => `- \`${r.source}\` → ${r.destination.map((d) => `\`${d}\``).join(', ') || '—'} (${r.status})${r.note ? `: ${r.note}` : ''}`),
    '',
    `## Server functions (${own.length})`,
    '',
    ...(own.length ? own.map(fnLine) : ['- none']),
    '',
    ...(states.length ? ['## User-visible states to keep', '', states.map((s) => `- ${s}`).join('\n'), ''] : []),
    '## Done when',
    '',
    '- Every route above reads and writes through real server functions or handlers, with typed search and path params.',
    '- Permissions match the canonical ones (admin checks in the handler, session and same-origin in the middleware), with tests for a viewer, an admin and no session.',
    '- Loading, empty, error, retry, redirect and session-expiry states behave as on mock data; the mock scenarios still work for design.',
    '- Unit, integration and browser checks pass, including `scripts/smoke.sh`.',
    '- The inventory rows above are marked real.',
  ].join('\n')
}

export function renderSlices(fns: ServerFn[], routes: RouteInventory[]): string {
  const numbers = issueNumbers()
  const lines = [
    '# Phase 2 slices',
    '',
    'The canonical dashboard cut into bounded migration issues by operator workflow (#6). Every canonical route module is in exactly one slice; a server function is in the slice of the routes that use it, and shared ones are in the shell slice. Generated by `scripts/inventory/slices.ts`.',
    '',
    '| Slice | Issue | Routes | Server functions | Mutations |',
    '|---|---|---|---|---|',
  ]
  for (const s of SLICES) {
    const own = fns.filter((f) => sliceOfFn(f, routes) === s.key)
    lines.push(`| ${s.title.replace(' (existing issue)', '')} | ${numbers[s.key] ? `#${numbers[s.key]}` : '—'} | ${s.routes.length} | ${own.length} | ${own.filter((f) => f.method === 'POST').length} |`)
  }
  lines.push('')
  return lines.join('\n')
}

if (import.meta.main) {
  const fns = read<ServerFn[]>('server-functions.json')
  const routes = read<RouteInventory[]>('routes.json')
  const canonical = readFileSync(join(dir, 'canonical-routes.txt'), 'utf8').split('\n').filter((l) => l && !l.startsWith('#'))
  const assigned = SLICES.flatMap((s) => s.routes)
  const unassigned = canonical.filter((r) => !assigned.includes(r))
  const doubled = assigned.filter((r, i) => assigned.indexOf(r) !== i)
  if (unassigned.length || doubled.length || assigned.length !== canonical.length) {
    console.error({ unassigned, doubled, assigned: assigned.length, canonical: canonical.length })
    process.exit(1)
  }
  if (process.argv.includes('--create')) {
    const numbers = issueNumbers()
    for (const s of SLICES) {
      if (numbers[s.key]) continue
      const result = Bun.spawnSync(['gh', 'issue', 'create', '--title', `Slice: ${s.title}`, '--label', 'migration', '--label', 'enhancement', '--body', body(s, fns, routes)])
      const url = result.stdout.toString().trim()
      const number = Number(/\/issues\/(\d+)$/.exec(url)?.[1])
      if (!number) throw new Error(`gh issue create failed for ${s.key}: ${result.stderr.toString()}`)
      numbers[s.key] = number
      const { security: _, ...kept } = numbers
      writeFileSync(join(dir, 'slices.json'), `${JSON.stringify(kept, null, 2)}\n`)
      console.log(`${s.key}: #${number}`)
    }
  }
  writeFileSync(join(dir, 'slices.md'), renderSlices(fns, routes))
  console.log(renderSlices(fns, routes))
}
